#红锋利
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"红锋利等级"=1}] ~~~ tag @a[scores={"分队"=1},x=-63,y=171,z=-63,dx=126,dy=33,dz=126,tag=!have_upgraded_sword_sharpness_i] add clear_wooden_sword
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"红锋利等级"=1}] ~~~ tag @a[scores={"分队"=1},x=-63,y=171,z=-63,dx=126,dy=33,dz=126,tag=!have_upgraded_sword_sharpness_i] add clear_stone_sword
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"红锋利等级"=1}] ~~~ tag @a[scores={"分队"=1},x=-63,y=171,z=-63,dx=126,dy=33,dz=126,tag=!have_upgraded_sword_sharpness_i] add clear_iron_sword
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"红锋利等级"=1}] ~~~ tag @a[scores={"分队"=1},x=-63,y=171,z=-63,dx=126,dy=33,dz=126,tag=!have_upgraded_sword_sharpness_i] add clear_diamond_sword
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"红锋利等级"=1}] ~~~ tag @a[scores={"分队"=1,"剑等级"=1},x=-63,y=171,z=-63,dx=126,dy=33,dz=126,tag=!have_upgraded_sword_sharpness_i] add give_wooden_sword_sharpness_i
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"红锋利等级"=1}] ~~~ tag @a[scores={"分队"=1,"剑等级"=2},x=-63,y=171,z=-63,dx=126,dy=33,dz=126,tag=!have_upgraded_sword_sharpness_i] add give_stone_sword_sharpness_i
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"红锋利等级"=1}] ~~~ tag @a[scores={"分队"=1,"剑等级"=3},x=-63,y=171,z=-63,dx=126,dy=33,dz=126,tag=!have_upgraded_sword_sharpness_i] add give_iron_sword_sharpness_i
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"红锋利等级"=1}] ~~~ tag @a[scores={"分队"=1,"剑等级"=4},x=-63,y=171,z=-63,dx=126,dy=33,dz=126,tag=!have_upgraded_sword_sharpness_i] add give_diamond_sword_sharpness_i
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"红锋利等级"=1}] ~~~ tag @a[scores={"分队"=1}] add have_upgraded_sword_sharpness_i
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"红锋利等级"=2}] ~~~ tag @a[scores={"分队"=1},x=-63,y=171,z=-63,dx=126,dy=33,dz=126,tag=!have_upgraded_sword_sharpness_ii] add clear_wooden_sword_sharpness_i
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"红锋利等级"=2}] ~~~ tag @a[scores={"分队"=1},x=-63,y=171,z=-63,dx=126,dy=33,dz=126,tag=!have_upgraded_sword_sharpness_ii] add clear_stone_sword_sharpness_i
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"红锋利等级"=2}] ~~~ tag @a[scores={"分队"=1},x=-63,y=171,z=-63,dx=126,dy=33,dz=126,tag=!have_upgraded_sword_sharpness_ii] add clear_iron_sword_sharpness_i
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"红锋利等级"=2}] ~~~ tag @a[scores={"分队"=1},x=-63,y=171,z=-63,dx=126,dy=33,dz=126,tag=!have_upgraded_sword_sharpness_ii] add clear_diamond_sword_sharpness_i
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"红锋利等级"=2}] ~~~ tag @a[scores={"分队"=1,"剑等级"=1},x=-63,y=171,z=-63,dx=126,dy=33,dz=126,tag=!have_upgraded_sword_sharpness_ii] add give_wooden_sword_sharpness_ii
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"红锋利等级"=2}] ~~~ tag @a[scores={"分队"=1,"剑等级"=2},x=-63,y=171,z=-63,dx=126,dy=33,dz=126,tag=!have_upgraded_sword_sharpness_ii] add give_stone_sword_sharpness_ii
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"红锋利等级"=2}] ~~~ tag @a[scores={"分队"=1,"剑等级"=3},x=-63,y=171,z=-63,dx=126,dy=33,dz=126,tag=!have_upgraded_sword_sharpness_ii] add give_iron_sword_sharpness_ii
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"红锋利等级"=2}] ~~~ tag @a[scores={"分队"=1,"剑等级"=4},x=-63,y=171,z=-63,dx=126,dy=33,dz=126,tag=!have_upgraded_sword_sharpness_ii] add give_diamond_sword_sharpness_ii
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"红锋利等级"=2}] ~~~ tag @a[scores={"分队"=1}] add have_upgraded_sword_sharpness_ii
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"红锋利等级"=3}] ~~~ tag @a[scores={"分队"=1},x=-63,y=171,z=-63,dx=126,dy=33,dz=126,tag=!have_upgraded_sword_sharpness_iii] add clear_wooden_sword_sharpness_ii
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"红锋利等级"=3}] ~~~ tag @a[scores={"分队"=1},x=-63,y=171,z=-63,dx=126,dy=33,dz=126,tag=!have_upgraded_sword_sharpness_iii] add clear_stone_sword_sharpness_ii
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"红锋利等级"=3}] ~~~ tag @a[scores={"分队"=1},x=-63,y=171,z=-63,dx=126,dy=33,dz=126,tag=!have_upgraded_sword_sharpness_iii] add clear_iron_sword_sharpness_ii
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"红锋利等级"=3}] ~~~ tag @a[scores={"分队"=1},x=-63,y=171,z=-63,dx=126,dy=33,dz=126,tag=!have_upgraded_sword_sharpness_iii] add clear_diamond_sword_sharpness_ii
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"红锋利等级"=3}] ~~~ tag @a[scores={"分队"=1,"剑等级"=1},x=-63,y=171,z=-63,dx=126,dy=33,dz=126,tag=!have_upgraded_sword_sharpness_iii] add give_wooden_sword_sharpness_iii
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"红锋利等级"=3}] ~~~ tag @a[scores={"分队"=1,"剑等级"=2},x=-63,y=171,z=-63,dx=126,dy=33,dz=126,tag=!have_upgraded_sword_sharpness_iii] add give_stone_sword_sharpness_iii
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"红锋利等级"=3}] ~~~ tag @a[scores={"分队"=1,"剑等级"=3},x=-63,y=171,z=-63,dx=126,dy=33,dz=126,tag=!have_upgraded_sword_sharpness_iii] add give_iron_sword_sharpness_iii
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"红锋利等级"=3}] ~~~ tag @a[scores={"分队"=1,"剑等级"=4},x=-63,y=171,z=-63,dx=126,dy=33,dz=126,tag=!have_upgraded_sword_sharpness_iii] add give_diamond_sword_sharpness_iii
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"红锋利等级"=3}] ~~~ tag @a[scores={"分队"=1}] add have_upgraded_sword_sharpness_iii
#蓝锋利
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"蓝锋利等级"=1}] ~~~ tag @a[scores={"分队"=2},x=-63,y=171,z=-63,dx=126,dy=33,dz=126,tag=!have_upgraded_sword_sharpness_i] add clear_wooden_sword
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"蓝锋利等级"=1}] ~~~ tag @a[scores={"分队"=2},x=-63,y=171,z=-63,dx=126,dy=33,dz=126,tag=!have_upgraded_sword_sharpness_i] add clear_stone_sword
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"蓝锋利等级"=1}] ~~~ tag @a[scores={"分队"=2},x=-63,y=171,z=-63,dx=126,dy=33,dz=126,tag=!have_upgraded_sword_sharpness_i] add clear_iron_sword
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"蓝锋利等级"=1}] ~~~ tag @a[scores={"分队"=2},x=-63,y=171,z=-63,dx=126,dy=33,dz=126,tag=!have_upgraded_sword_sharpness_i] add clear_diamond_sword
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"蓝锋利等级"=1}] ~~~ tag @a[scores={"分队"=2,"剑等级"=1},x=-63,y=171,z=-63,dx=126,dy=33,dz=126,tag=!have_upgraded_sword_sharpness_i] add give_wooden_sword_sharpness_i
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"蓝锋利等级"=1}] ~~~ tag @a[scores={"分队"=2,"剑等级"=2},x=-63,y=171,z=-63,dx=126,dy=33,dz=126,tag=!have_upgraded_sword_sharpness_i] add give_stone_sword_sharpness_i
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"蓝锋利等级"=1}] ~~~ tag @a[scores={"分队"=2,"剑等级"=3},x=-63,y=171,z=-63,dx=126,dy=33,dz=126,tag=!have_upgraded_sword_sharpness_i] add give_iron_sword_sharpness_i
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"蓝锋利等级"=1}] ~~~ tag @a[scores={"分队"=2,"剑等级"=4},x=-63,y=171,z=-63,dx=126,dy=33,dz=126,tag=!have_upgraded_sword_sharpness_i] add give_diamond_sword_sharpness_i
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"蓝锋利等级"=1}] ~~~ tag @a[scores={"分队"=2}] add have_upgraded_sword_sharpness_i
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"蓝锋利等级"=2}] ~~~ tag @a[scores={"分队"=2},x=-63,y=171,z=-63,dx=126,dy=33,dz=126,tag=!have_upgraded_sword_sharpness_ii] add clear_wooden_sword_sharpness_i
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"蓝锋利等级"=2}] ~~~ tag @a[scores={"分队"=2},x=-63,y=171,z=-63,dx=126,dy=33,dz=126,tag=!have_upgraded_sword_sharpness_ii] add clear_stone_sword_sharpness_i
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"蓝锋利等级"=2}] ~~~ tag @a[scores={"分队"=2},x=-63,y=171,z=-63,dx=126,dy=33,dz=126,tag=!have_upgraded_sword_sharpness_ii] add clear_iron_sword_sharpness_i
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"蓝锋利等级"=2}] ~~~ tag @a[scores={"分队"=2},x=-63,y=171,z=-63,dx=126,dy=33,dz=126,tag=!have_upgraded_sword_sharpness_ii] add clear_diamond_sword_sharpness_i
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"蓝锋利等级"=2}] ~~~ tag @a[scores={"分队"=2,"剑等级"=1},x=-63,y=171,z=-63,dx=126,dy=33,dz=126,tag=!have_upgraded_sword_sharpness_ii] add give_wooden_sword_sharpness_ii
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"蓝锋利等级"=2}] ~~~ tag @a[scores={"分队"=2,"剑等级"=2},x=-63,y=171,z=-63,dx=126,dy=33,dz=126,tag=!have_upgraded_sword_sharpness_ii] add give_stone_sword_sharpness_ii
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"蓝锋利等级"=2}] ~~~ tag @a[scores={"分队"=2,"剑等级"=3},x=-63,y=171,z=-63,dx=126,dy=33,dz=126,tag=!have_upgraded_sword_sharpness_ii] add give_iron_sword_sharpness_ii
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"蓝锋利等级"=2}] ~~~ tag @a[scores={"分队"=2,"剑等级"=4},x=-63,y=171,z=-63,dx=126,dy=33,dz=126,tag=!have_upgraded_sword_sharpness_ii] add give_diamond_sword_sharpness_ii
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"蓝锋利等级"=2}] ~~~ tag @a[scores={"分队"=2}] add have_upgraded_sword_sharpness_ii
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"蓝锋利等级"=3}] ~~~ tag @a[scores={"分队"=2},x=-63,y=171,z=-63,dx=126,dy=33,dz=126,tag=!have_upgraded_sword_sharpness_iii] add clear_wooden_sword_sharpness_ii
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"蓝锋利等级"=3}] ~~~ tag @a[scores={"分队"=2},x=-63,y=171,z=-63,dx=126,dy=33,dz=126,tag=!have_upgraded_sword_sharpness_iii] add clear_stone_sword_sharpness_ii
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"蓝锋利等级"=3}] ~~~ tag @a[scores={"分队"=2},x=-63,y=171,z=-63,dx=126,dy=33,dz=126,tag=!have_upgraded_sword_sharpness_iii] add clear_iron_sword_sharpness_ii
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"蓝锋利等级"=3}] ~~~ tag @a[scores={"分队"=2},x=-63,y=171,z=-63,dx=126,dy=33,dz=126,tag=!have_upgraded_sword_sharpness_iii] add clear_diamond_sword_sharpness_ii
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"蓝锋利等级"=3}] ~~~ tag @a[scores={"分队"=2,"剑等级"=1},x=-63,y=171,z=-63,dx=126,dy=33,dz=126,tag=!have_upgraded_sword_sharpness_iii] add give_wooden_sword_sharpness_iii
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"蓝锋利等级"=3}] ~~~ tag @a[scores={"分队"=2,"剑等级"=2},x=-63,y=171,z=-63,dx=126,dy=33,dz=126,tag=!have_upgraded_sword_sharpness_iii] add give_stone_sword_sharpness_iii
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"蓝锋利等级"=3}] ~~~ tag @a[scores={"分队"=2,"剑等级"=3},x=-63,y=171,z=-63,dx=126,dy=33,dz=126,tag=!have_upgraded_sword_sharpness_iii] add give_iron_sword_sharpness_iii
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"蓝锋利等级"=3}] ~~~ tag @a[scores={"分队"=2,"剑等级"=4},x=-63,y=171,z=-63,dx=126,dy=33,dz=126,tag=!have_upgraded_sword_sharpness_iii] add give_diamond_sword_sharpness_iii
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"蓝锋利等级"=3}] ~~~ tag @a[scores={"分队"=2}] add have_upgraded_sword_sharpness_iii
#黄锋利
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"黄锋利等级"=1}] ~~~ tag @a[scores={"分队"=3},x=-63,y=171,z=-63,dx=126,dy=33,dz=126,tag=!have_upgraded_sword_sharpness_i] add clear_wooden_sword
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"黄锋利等级"=1}] ~~~ tag @a[scores={"分队"=3},x=-63,y=171,z=-63,dx=126,dy=33,dz=126,tag=!have_upgraded_sword_sharpness_i] add clear_stone_sword
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"黄锋利等级"=1}] ~~~ tag @a[scores={"分队"=3},x=-63,y=171,z=-63,dx=126,dy=33,dz=126,tag=!have_upgraded_sword_sharpness_i] add clear_iron_sword
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"黄锋利等级"=1}] ~~~ tag @a[scores={"分队"=3},x=-63,y=171,z=-63,dx=126,dy=33,dz=126,tag=!have_upgraded_sword_sharpness_i] add clear_diamond_sword
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"黄锋利等级"=1}] ~~~ tag @a[scores={"分队"=3,"剑等级"=1},x=-63,y=171,z=-63,dx=126,dy=33,dz=126,tag=!have_upgraded_sword_sharpness_i] add give_wooden_sword_sharpness_i
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"黄锋利等级"=1}] ~~~ tag @a[scores={"分队"=3,"剑等级"=2},x=-63,y=171,z=-63,dx=126,dy=33,dz=126,tag=!have_upgraded_sword_sharpness_i] add give_stone_sword_sharpness_i
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"黄锋利等级"=1}] ~~~ tag @a[scores={"分队"=3,"剑等级"=3},x=-63,y=171,z=-63,dx=126,dy=33,dz=126,tag=!have_upgraded_sword_sharpness_i] add give_iron_sword_sharpness_i
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"黄锋利等级"=1}] ~~~ tag @a[scores={"分队"=3,"剑等级"=4},x=-63,y=171,z=-63,dx=126,dy=33,dz=126,tag=!have_upgraded_sword_sharpness_i] add give_diamond_sword_sharpness_i
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"黄锋利等级"=1}] ~~~ tag @a[scores={"分队"=3}] add have_upgraded_sword_sharpness_i
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"黄锋利等级"=2}] ~~~ tag @a[scores={"分队"=3},x=-63,y=171,z=-63,dx=126,dy=33,dz=126,tag=!have_upgraded_sword_sharpness_ii] add give_wooden_sword_sharpness_i
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"黄锋利等级"=2}] ~~~ tag @a[scores={"分队"=3},x=-63,y=171,z=-63,dx=126,dy=33,dz=126,tag=!have_upgraded_sword_sharpness_ii] add give_stone_sword_sharpness_i
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"黄锋利等级"=2}] ~~~ tag @a[scores={"分队"=3},x=-63,y=171,z=-63,dx=126,dy=33,dz=126,tag=!have_upgraded_sword_sharpness_ii] add give_iron_sword_sharpness_i
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"黄锋利等级"=2}] ~~~ tag @a[scores={"分队"=3},x=-63,y=171,z=-63,dx=126,dy=33,dz=126,tag=!have_upgraded_sword_sharpness_ii] add give_diamond_sword_sharpness_i
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"黄锋利等级"=2}] ~~~ tag @a[scores={"分队"=3,"剑等级"=1},x=-63,y=171,z=-63,dx=126,dy=33,dz=126,tag=!have_upgraded_sword_sharpness_ii] add give_wooden_sword_sharpness_ii
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"黄锋利等级"=2}] ~~~ tag @a[scores={"分队"=3,"剑等级"=2},x=-63,y=171,z=-63,dx=126,dy=33,dz=126,tag=!have_upgraded_sword_sharpness_ii] add give_stone_sword_sharpness_ii
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"黄锋利等级"=2}] ~~~ tag @a[scores={"分队"=3,"剑等级"=3},x=-63,y=171,z=-63,dx=126,dy=33,dz=126,tag=!have_upgraded_sword_sharpness_ii] add give_iron_sword_sharpness_ii
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"黄锋利等级"=2}] ~~~ tag @a[scores={"分队"=3,"剑等级"=4},x=-63,y=171,z=-63,dx=126,dy=33,dz=126,tag=!have_upgraded_sword_sharpness_ii] add give_diamond_sword_sharpness_ii
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"黄锋利等级"=2}] ~~~ tag @a[scores={"分队"=3}] add have_upgraded_sword_sharpness_ii
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"黄锋利等级"=3}] ~~~ tag @a[scores={"分队"=3},x=-63,y=171,z=-63,dx=126,dy=33,dz=126,tag=!have_upgraded_sword_sharpness_iii] add clear_wooden_sword_sharpness_ii
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"黄锋利等级"=3}] ~~~ tag @a[scores={"分队"=3},x=-63,y=171,z=-63,dx=126,dy=33,dz=126,tag=!have_upgraded_sword_sharpness_iii] add clear_stone_sword_sharpness_ii
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"黄锋利等级"=3}] ~~~ tag @a[scores={"分队"=3},x=-63,y=171,z=-63,dx=126,dy=33,dz=126,tag=!have_upgraded_sword_sharpness_iii] add clear_iron_sword_sharpness_ii
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"黄锋利等级"=3}] ~~~ tag @a[scores={"分队"=3},x=-63,y=171,z=-63,dx=126,dy=33,dz=126,tag=!have_upgraded_sword_sharpness_iii] add clear_diamond_sword_sharpness_ii
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"黄锋利等级"=3}] ~~~ tag @a[scores={"分队"=3,"剑等级"=1},x=-63,y=171,z=-63,dx=126,dy=33,dz=126,tag=!have_upgraded_sword_sharpness_iii] add give_wooden_sword_sharpness_iii
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"黄锋利等级"=3}] ~~~ tag @a[scores={"分队"=3,"剑等级"=2},x=-63,y=171,z=-63,dx=126,dy=33,dz=126,tag=!have_upgraded_sword_sharpness_iii] add give_stone_sword_sharpness_iii
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"黄锋利等级"=3}] ~~~ tag @a[scores={"分队"=3,"剑等级"=3},x=-63,y=171,z=-63,dx=126,dy=33,dz=126,tag=!have_upgraded_sword_sharpness_iii] add give_iron_sword_sharpness_iii
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"黄锋利等级"=3}] ~~~ tag @a[scores={"分队"=3,"剑等级"=4},x=-63,y=171,z=-63,dx=126,dy=33,dz=126,tag=!have_upgraded_sword_sharpness_iii] add give_diamond_sword_sharpness_iii
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"黄锋利等级"=3}] ~~~ tag @a[scores={"分队"=3}] add have_upgraded_sword_sharpness_iii
#绿锋利
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"绿锋利等级"=1}] ~~~ tag @a[scores={"分队"=4},x=-63,y=171,z=-63,dx=126,dy=33,dz=126,tag=!have_upgraded_sword_sharpness_i] add clear_wooden_sword
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"绿锋利等级"=1}] ~~~ tag @a[scores={"分队"=4},x=-63,y=171,z=-63,dx=126,dy=33,dz=126,tag=!have_upgraded_sword_sharpness_i] add clear_stone_sword
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"绿锋利等级"=1}] ~~~ tag @a[scores={"分队"=4},x=-63,y=171,z=-63,dx=126,dy=33,dz=126,tag=!have_upgraded_sword_sharpness_i] add clear_iron_sword
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"绿锋利等级"=1}] ~~~ tag @a[scores={"分队"=4},x=-63,y=171,z=-63,dx=126,dy=33,dz=126,tag=!have_upgraded_sword_sharpness_i] add clear_diamond_sword
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"绿锋利等级"=1}] ~~~ tag @a[scores={"分队"=4,"剑等级"=1},x=-63,y=171,z=-63,dx=126,dy=33,dz=126,tag=!have_upgraded_sword_sharpness_i] add give_wooden_sword_sharpness_i
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"绿锋利等级"=1}] ~~~ tag @a[scores={"分队"=4,"剑等级"=2},x=-63,y=171,z=-63,dx=126,dy=33,dz=126,tag=!have_upgraded_sword_sharpness_i] add give_stone_sword_sharpness_i
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"绿锋利等级"=1}] ~~~ tag @a[scores={"分队"=4,"剑等级"=3},x=-63,y=171,z=-63,dx=126,dy=33,dz=126,tag=!have_upgraded_sword_sharpness_i] add give_iron_sword_sharpness_i
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"绿锋利等级"=1}] ~~~ tag @a[scores={"分队"=4,"剑等级"=4},x=-63,y=171,z=-63,dx=126,dy=33,dz=126,tag=!have_upgraded_sword_sharpness_i] add give_diamond_sword_sharpness_i
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"绿锋利等级"=1}] ~~~ tag @a[scores={"分队"=4}] add have_upgraded_sword_sharpness_i
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"绿锋利等级"=2}] ~~~ tag @a[scores={"分队"=4},x=-63,y=171,z=-63,dx=126,dy=33,dz=126,tag=!have_upgraded_sword_sharpness_ii] add clear_wooden_sword_sharpness_i
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"绿锋利等级"=2}] ~~~ tag @a[scores={"分队"=4},x=-63,y=171,z=-63,dx=126,dy=33,dz=126,tag=!have_upgraded_sword_sharpness_ii] add clear_stone_sword_sharpness_i
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"绿锋利等级"=2}] ~~~ tag @a[scores={"分队"=4},x=-63,y=171,z=-63,dx=126,dy=33,dz=126,tag=!have_upgraded_sword_sharpness_ii] add clear_iron_sword_sharpness_i
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"绿锋利等级"=2}] ~~~ tag @a[scores={"分队"=4},x=-63,y=171,z=-63,dx=126,dy=33,dz=126,tag=!have_upgraded_sword_sharpness_ii] add clear_diamond_sword_sharpness_i
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"绿锋利等级"=2}] ~~~ tag @a[scores={"分队"=4,"剑等级"=1},x=-63,y=171,z=-63,dx=126,dy=33,dz=126,tag=!have_upgraded_sword_sharpness_ii] add give_wooden_sword_sharpness_ii
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"绿锋利等级"=2}] ~~~ tag @a[scores={"分队"=4,"剑等级"=2},x=-63,y=171,z=-63,dx=126,dy=33,dz=126,tag=!have_upgraded_sword_sharpness_ii] add give_stone_sword_sharpness_ii
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"绿锋利等级"=2}] ~~~ tag @a[scores={"分队"=4,"剑等级"=3},x=-63,y=171,z=-63,dx=126,dy=33,dz=126,tag=!have_upgraded_sword_sharpness_ii] add give_iron_sword_sharpness_ii
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"绿锋利等级"=2}] ~~~ tag @a[scores={"分队"=4,"剑等级"=4},x=-63,y=171,z=-63,dx=126,dy=33,dz=126,tag=!have_upgraded_sword_sharpness_ii] add give_diamond_sword_sharpness_ii
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"绿锋利等级"=2}] ~~~ tag @a[scores={"分队"=4}] add have_upgraded_sword_sharpness_ii
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"绿锋利等级"=3}] ~~~ tag @a[scores={"分队"=4},x=-63,y=171,z=-63,dx=126,dy=33,dz=126,tag=!have_upgraded_sword_sharpness_iii] add clear_wooden_sword_sharpness_ii
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"绿锋利等级"=3}] ~~~ tag @a[scores={"分队"=4},x=-63,y=171,z=-63,dx=126,dy=33,dz=126,tag=!have_upgraded_sword_sharpness_iii] add clear_stone_sword_sharpness_ii
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"绿锋利等级"=3}] ~~~ tag @a[scores={"分队"=4},x=-63,y=171,z=-63,dx=126,dy=33,dz=126,tag=!have_upgraded_sword_sharpness_iii] add clear_iron_sword_sharpness_ii
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"绿锋利等级"=3}] ~~~ tag @a[scores={"分队"=4},x=-63,y=171,z=-63,dx=126,dy=33,dz=126,tag=!have_upgraded_sword_sharpness_iii] add clear_diamond_sword_sharpness_ii
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"绿锋利等级"=3}] ~~~ tag @a[scores={"分队"=4,"剑等级"=1},x=-63,y=171,z=-63,dx=126,dy=33,dz=126,tag=!have_upgraded_sword_sharpness_iii] add give_wooden_sword_sharpness_iii  
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"绿锋利等级"=3}] ~~~ tag @a[scores={"分队"=4,"剑等级"=2},x=-63,y=171,z=-63,dx=126,dy=33,dz=126,tag=!have_upgraded_sword_sharpness_iii] add give_stone_sword_sharpness_iii   
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"绿锋利等级"=3}] ~~~ tag @a[scores={"分队"=4,"剑等级"=3},x=-63,y=171,z=-63,dx=126,dy=33,dz=126,tag=!have_upgraded_sword_sharpness_iii] add give_iron_sword_sharpness_iii    
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"绿锋利等级"=3}] ~~~ tag @a[scores={"分队"=4,"剑等级"=4},x=-63,y=171,z=-63,dx=126,dy=33,dz=126,tag=!have_upgraded_sword_sharpness_iii] add give_diamond_sword_sharpness_iii 
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"绿锋利等级"=3}] ~~~ tag @a[scores={"分队"=4}] add have_upgraded_sword_sharpness_iii
execute @a[scores={"分队"=1..4}] function shop_purchase/upgrade_team_clear_items
execute @a[scores={"分队"=1..4}] function shop_purchase/upgrade_team_give_items