# 升级到石剑
execute @e[type=armor_stand,scores={gameSTART=1,"红锋利等级"=0},name=main] ~~~ execute @e[type=player,tag=up_sword,scores={"剑等级"=1,"分队"=1}] ~~~ clear @s wooden_sword
execute @e[type=armor_stand,scores={gameSTART=1,"红锋利等级"=0},name=main] ~~~ execute @e[type=player,tag=up_sword,scores={"剑等级"=1,"分队"=1}] ~~~ give @s stone_sword 1 0 {"minecraft:item_lock":{"mode":"lock_in_inventory"},"minecraft:keep_on_death":{}}
execute @e[type=armor_stand,scores={gameSTART=1,"红锋利等级"=1},name=main] ~~~ execute @e[type=player,tag=up_sword,scores={"剑等级"=1,"分队"=1}] ~~~ clear @s bedwars:wooden_sword_sharpnessI
execute @e[type=armor_stand,scores={gameSTART=1,"红锋利等级"=1},name=main] ~~~ execute @e[type=player,tag=up_sword,scores={"剑等级"=1,"分队"=1}] ~~~ give @s bedwars:stone_sword_sharpnessI 1 0 {"minecraft:item_lock":{"mode":"lock_in_inventory"},"minecraft:keep_on_death":{}}
execute @e[type=armor_stand,scores={gameSTART=1,"红锋利等级"=2},name=main] ~~~ execute @e[type=player,tag=up_sword,scores={"剑等级"=1,"分队"=1}] ~~~ clear @s bedwars:wooden_sword_sharpnessII
execute @e[type=armor_stand,scores={gameSTART=1,"红锋利等级"=2},name=main] ~~~ execute @e[type=player,tag=up_sword,scores={"剑等级"=1,"分队"=1}] ~~~ give @s bedwars:stone_sword_sharpnessII 1 0 {"minecraft:item_lock":{"mode":"lock_in_inventory"},"minecraft:keep_on_death":{}}
execute @e[type=armor_stand,scores={gameSTART=1,"红锋利等级"=3},name=main] ~~~ execute @e[type=player,tag=up_sword,scores={"剑等级"=1,"分队"=1}] ~~~ clear @s bedwars:wooden_sword_sharpnessIII
execute @e[type=armor_stand,scores={gameSTART=1,"红锋利等级"=3},name=main] ~~~ execute @e[type=player,tag=up_sword,scores={"剑等级"=1,"分队"=1}] ~~~ give @s bedwars:stone_sword_sharpnessIII 1 0 {"minecraft:item_lock":{"mode":"lock_in_inventory"},"minecraft:keep_on_death":{}}
execute @e[type=armor_stand,scores={gameSTART=1,"蓝锋利等级"=0},name=main] ~~~ execute @e[type=player,tag=up_sword,scores={"剑等级"=1,"分队"=2}] ~~~ clear @s wooden_sword
execute @e[type=armor_stand,scores={gameSTART=1,"蓝锋利等级"=0},name=main] ~~~ execute @e[type=player,tag=up_sword,scores={"剑等级"=1,"分队"=2}] ~~~ give @s stone_sword 1 0 {"minecraft:item_lock":{"mode":"lock_in_inventory"},"minecraft:keep_on_death":{}}
execute @e[type=armor_stand,scores={gameSTART=1,"蓝锋利等级"=1},name=main] ~~~ execute @e[type=player,tag=up_sword,scores={"剑等级"=1,"分队"=2}] ~~~ clear @s bedwars:wooden_sword_sharpnessI
execute @e[type=armor_stand,scores={gameSTART=1,"蓝锋利等级"=1},name=main] ~~~ execute @e[type=player,tag=up_sword,scores={"剑等级"=1,"分队"=2}] ~~~ give @s bedwars:stone_sword_sharpnessI 1 0 {"minecraft:item_lock":{"mode":"lock_in_inventory"},"minecraft:keep_on_death":{}}
execute @e[type=armor_stand,scores={gameSTART=1,"蓝锋利等级"=2},name=main] ~~~ execute @e[type=player,tag=up_sword,scores={"剑等级"=1,"分队"=2}] ~~~ clear @s bedwars:wooden_sword_sharpnessII
execute @e[type=armor_stand,scores={gameSTART=1,"蓝锋利等级"=2},name=main] ~~~ execute @e[type=player,tag=up_sword,scores={"剑等级"=1,"分队"=2}] ~~~ give @s bedwars:stone_sword_sharpnessII 1 0 {"minecraft:item_lock":{"mode":"lock_in_inventory"},"minecraft:keep_on_death":{}}
execute @e[type=armor_stand,scores={gameSTART=1,"蓝锋利等级"=3},name=main] ~~~ execute @e[type=player,tag=up_sword,scores={"剑等级"=1,"分队"=2}] ~~~ clear @s bedwars:wooden_sword_sharpnessIII
execute @e[type=armor_stand,scores={gameSTART=1,"蓝锋利等级"=3},name=main] ~~~ execute @e[type=player,tag=up_sword,scores={"剑等级"=1,"分队"=2}] ~~~ give @s bedwars:stone_sword_sharpnessIII 1 0 {"minecraft:item_lock":{"mode":"lock_in_inventory"},"minecraft:keep_on_death":{}}
execute @e[type=armor_stand,scores={gameSTART=1},name=main] ~~~ execute @e[type=player,tag=up_sword,scores={"剑等级"=1}] ~~~ scoreboard players set @s "剑等级" 2
execute @e[type=armor_stand,scores={gameSTART=1},name=main] ~~~ execute @e[type=player,tag=up_sword,scores={"剑等级"=2}] ~~~ tellraw @s { "rawtext" : [ { "text" : "§f商店 >> §7§l您的剑已升级为等级 2 §f(石质)" } ] }
execute @e[type=armor_stand,scores={gameSTART=1},name=main] ~~~ execute @e[type=player,tag=up_sword,scores={"剑等级"=2}] ~~~ tag @s remove up_sword