scoreboard objectives add "黄床存活" dummy
scoreboard objectives add "黄床有敌" dummy
scoreboard objectives add "绿床存活" dummy
scoreboard objectives add "绿床有敌" dummy
scoreboard objectives add 红队存在 dummy
scoreboard objectives add 黄队存在 dummy
scoreboard objectives add 蓝队存在 dummy
scoreboard objectives add 绿队存在 dummy
scoreboard objectives add 红剩人数 dummy
scoreboard objectives add 黄剩人数 dummy
scoreboard objectives add 蓝剩人数 dummy
scoreboard objectives add 绿剩人数 dummy
scoreboard objectives add 红已重置 dummy
scoreboard objectives add 黄已重置 dummy
scoreboard objectives add 蓝已重置 dummy
scoreboard objectives add 绿已重置 dummy
scoreboard objectives add 黄铁time dummy
scoreboard objectives add 绿铁time dummy
scoreboard objectives add 黄家金time dummy
scoreboard objectives add 绿家金time dummy
scoreboard objectives add Y_spawned_iron_1 dummy
scoreboard objectives add Y_spawned_iron_2 dummy
scoreboard objectives add Y_spawned_iron_3 dummy
scoreboard objectives add Y_spawned_gold dummy
scoreboard objectives add Y_iron_count_1 dummy
scoreboard objectives add Y_iron_count_2 dummy
scoreboard objectives add Y_iron_count_3 dummy
scoreboard objectives add Y_gold_count dummy
scoreboard objectives add G_spawned_iron_1 dummy
scoreboard objectives add G_spawned_iron_2 dummy
scoreboard objectives add G_spawned_iron_3 dummy
scoreboard objectives add G_spawned_gold dummy
scoreboard objectives add G_iron_count_1 dummy
scoreboard objectives add G_iron_count_2 dummy
scoreboard objectives add G_iron_count_3 dummy
scoreboard objectives add G_gold_count dummy
scoreboard objectives add 黄保护等级 dummy
scoreboard objectives add 黄锋利等级 dummy
scoreboard objectives add 黄陷阱等级 dummy
scoreboard objectives add 绿保护等级 dummy
scoreboard objectives add 绿锋利等级 dummy
scoreboard objectives add 绿陷阱等级 dummy
scoreboard objectives add xp_cache dummy
scoreboard objectives add got_xp dummy
scoreboard objectives add after_g_en_exist dummy
scoreboard objectives add invisible_time dummy
scoreboard objectives add 钻已重置 dummy
scoreboard objectives add 中已重置 dummy
scoreboard objectives add 保已重置 dummy
scoreboard objectives add 多已删除 dummy
scoreboard objectives add joined dummy
scoreboard objectives add game_version dummy
scoreboard players set @e[type=armor_stand,name=main] game_version 2